name: Run every scan
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps: 
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build with gradle
        run: ./gradlew clean build
  zap-scan:
    runs-on: ubuntu-latest
    needs: build
    name: Run DAST scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'